<?php

namespace App\Permissions;

use App\Enums\PERMISSIONS;

class AllPermissions
{
  public $superadmin = [
    PERMISSIONS::CREATE_USER->value,
    PERMISSIONS::CREATE_TASK->value,
    PERMISSIONS::CREATE_COMMENT->value,
    PERMISSIONS::CREATE_FILE->value,

    PERMISSIONS::GET_USERS->value,
    PERMISSIONS::GET_TASKS->value,
    PERMISSIONS::GET_COMMENTS->value,
    PERMISSIONS::GET_FILES->value,

    PERMISSIONS::UPDATE_USER->value,
    PERMISSIONS::UPDATE_TASK->value,
    PERMISSIONS::UPDATE_COMMENT->value,

    PERMISSIONS::DELETE_USER->value,
    PERMISSIONS::DELETE_TASK->value,
    PERMISSIONS::DELETE_COMMENT->value,
    PERMISSIONS::DELETE_FILE->value,

    PERMISSIONS::SEND_REPORT->value,
  ];

  public $employee = [
    PERMISSIONS::CREATE_COMMENT->value,
    PERMISSIONS::CREATE_FILE->value,

    PERMISSIONS::GET_USERS->value,
    PERMISSIONS::GET_TASKS->value,
    PERMISSIONS::GET_COMMENTS->value,
    PERMISSIONS::GET_FILES->value,

    PERMISSIONS::UPDATE_COMMENT->value,

    PERMISSIONS::DELETE_COMMENT->value,
    PERMISSIONS::DELETE_FILE->value
  ];
}
